/* exported SERVER_TOUR_DATA */
/**
 * GPU Server Tour – slide and hotspot data.
 *
 * Data schema (see CONTRIBUTING.md for full documentation):
 *
 * @typedef {Object} HotspotContent
 * @property {string} title - Title shown in the popup
 * @property {string} what - What the component is (1–2 sentences)
 * @property {string} role - What the component does (1–2 sentences)
 * @property {string} [integration] - Optional extra text (e.g. integration notes)
 *
 * @typedef {Object} Hotspot
 * @property {string} id - Unique identifier for the hotspot
 * @property {string} label - Human-readable label (used for ARIA and tooltips)
 * @property {number[]} pointsPx - Polygon coordinates as flat list: [x1, y1, x2, y2, ...] in source image pixels
 * @property {number} sourceWidth - Width in pixels of the image the coordinates were drawn against
 * @property {number} sourceHeight - Height in pixels of the image the coordinates were drawn against
 * @property {HotspotContent} content - Popup title and body text
 * @property {number[][]} [points] - Optional: polygon as percentage pairs [[x%, y%], ...]; used if pointsPx is absent
 * @property {number} [adjustOffsetX] - Optional: pixel offset to fine-tune overlay position (X)
 * @property {number} [adjustOffsetY] - Optional: pixel offset to fine-tune overlay position (Y)
 * @property {number} [adjustScaleX] - Optional: scale factor around polygon centroid (X) for alignment
 * @property {number} [adjustScaleY] - Optional: scale factor around polygon centroid (Y) for alignment
 *
 * @typedef {Object} TourImage
 * @property {string} id - Unique id for the slide (e.g. "front", "top", "back")
 * @property {string} src - Path to the image file (e.g. "images/front.png")
 * @property {string} alt - Accessible description of the image
 * @property {Hotspot[]} hotspots - Array of clickable polygon regions
 *
 * @typedef {Object} ServerTourData
 * @property {TourImage[]} images - Ordered list of slides
 * @property {number} [defaultAdjustOffsetX] - Optional global default for hotspot adjustOffsetX
 * @property {number} [defaultAdjustOffsetY] - Optional global default for hotspot adjustOffsetY
 *
 * HOW TO ADD A POLYGON BORDER (using pixel coordinates):
 * 1. Open your image in an editor that shows pixel coordinates (e.g. Photoshop, GIMP, or an online image map tool).
 * 2. Note the image dimensions (width × height in pixels).
 * 3. Draw your polygon and copy the coordinates as a flat list:
 *    x1, y1, x2, y2, x3, y3, ... (clockwise or anti-clockwise order)
 * 4. In data.js add a hotspot with:
 *    - pointsPx: [ x1, y1, x2, y2, ... ]
 *    - sourceWidth:  (the image width from step 2)
 *    - sourceHeight: (the image height from step 2)
 *    - label, content, etc.
 *
 * Example polygon format (for a 4-corner shape):
 *   pointsPx: [100, 200, 300, 200, 300, 400, 100, 400],
 *   sourceWidth: 800,
 *   sourceHeight: 600,
 *
 * The app will automatically scale your coordinates to match the displayed image size.
 */

/** @type {ServerTourData} */
const SERVER_TOUR_DATA = {
  images: [
    {
      id: "front",
      src: "images/front.png",
      alt: "GPU server, front view – drive bays and ventilation",
      hotspots: [
        {
          id: "fan-cooling-tower",
          label: "Fan + cooling tower assembly",
          pointsPx: [
            808, 503, 828, 504, 863, 483, 955, 483, 994, 499, 1015, 499, 1073,
            605, 1091, 658, 1042, 805, 1014, 808, 1008, 867, 829, 861, 821, 801,
            805, 751, 791, 668,
          ],
          sourceWidth: 1280,
          sourceHeight: 963,
          content: {
            title: "Fan + cooling tower assembly",
            what: "A cooling tower with an attached fan that draws air through the server to remove heat generated by components.",
            role: "Keeps the CPU and other components within safe operating temperatures during heavy workloads.",
          },
        },
        {
          id: "host-memory-1",
          label: "Host memory (RAM)",
          pointsPx: [675, 623, 685, 888, 830, 891, 787, 623],
          sourceWidth: 1280,
          sourceHeight: 963,
          content: {
            title: "Host memory (RAM)",
            what: "DDR memory modules that provide fast, temporary storage for data and code the CPU is actively processing.",
            role: "Enables quick access to data for the CPU, improving overall system performance and responsiveness.",
          },
        },
        {
          id: "host-memory-2",
          label: "Host memory (RAM)",
          pointsPx: [548, 625, 517, 887, 667, 889, 661, 625],
          sourceWidth: 1280,
          sourceHeight: 963,
          content: {
            title: "Host memory (RAM)",
            what: "DDR memory modules that provide fast, temporary storage for data and code the CPU is actively processing.",
            role: "Enables quick access to data for the CPU, improving overall system performance and responsiveness.",
          },
        },
        {
          id: "host-memory-3",
          label: "Host memory (RAM)",
          pointsPx: [280, 630, 399, 630, 332, 882, 172, 866],
          sourceWidth: 1280,
          sourceHeight: 963,
          content: {
            title: "Host memory (RAM)",
            what: "DDR memory modules that provide fast, temporary storage for data and code the CPU is actively processing.",
            role: "Enables quick access to data for the CPU, improving overall system performance and responsiveness.",
          },
        },
        {
          id: "host-memory-4",
          label: "Host memory (RAM)",
          pointsPx: [1176, 895, 1025, 892, 1020, 818, 1052, 815, 1098, 669],
          sourceWidth: 1280,
          sourceHeight: 963,
          content: {
            title: "Host memory (RAM)",
            what: "DDR memory modules that provide fast, temporary storage for data and code the CPU is actively processing.",
            role: "Enables quick access to data for the CPU, improving overall system performance and responsiveness.",
          },
        },
        {
          id: "pcie-gpu-1",
          label: "PCIe GPU",
          pointsPx: [
            583, 182, 632, 182, 643, 314, 636, 493, 557, 490, 552, 345,
          ],
          sourceWidth: 1280,
          sourceHeight: 963,
          content: {
            title: "PCIe GPU",
            what: "A graphics processing unit installed in a PCIe slot, containing the GPU chip, memory, and power delivery components.",
            role: "Accelerates parallel computing tasks like AI training, inference, and scientific simulations.",
          },
        },
        {
          id: "pcie-gpu-2",
          label: "PCIe GPU",
          pointsPx: [
            770, 175, 765, 325, 798, 494, 860, 494, 875, 360, 809, 168,
          ],
          sourceWidth: 1280,
          sourceHeight: 963,
          content: {
            title: "PCIe GPU",
            what: "A graphics processing unit installed in a PCIe slot, containing the GPU chip, memory, and power delivery components.",
            role: "Accelerates parallel computing tasks like AI training, inference, and scientific simulations.",
          },
        },
        {
          id: "cpu",
          label: "CPU",
          pointsPx: [403, 668, 539, 668, 517, 838, 356, 822],
          sourceWidth: 1280,
          sourceHeight: 963,
          content: {
            title: "CPU",
            what: "The central processing unit is the main processor that runs the operating system and coordinates all hardware components.",
            role: "Executes instructions, manages system resources, and handles workloads not suited for GPU acceleration.",
          },
        },
        {
          id: "nic",
          label: "NIC",
          pointsPx: [
            443, 179, 447, 244, 417, 322, 434, 401, 464, 402, 487, 305, 473,
            179,
          ],
          sourceWidth: 1280,
          sourceHeight: 963,
          content: {
            title: "NIC",
            what: "A network interface card that provides network connectivity for data transfer to and from the server.",
            role: "Enables high-speed network communication for data ingestion, model serving, and cluster coordination.",
          },
        },
      ],
    },
    {
      id: "top",
      src: "images/top.png",
      alt: "GPU server with top removed – view of GPUs, CPUs, RAM, and drive bays",
      hotspots: [
        {
          id: "pcie-gpu-1-top",
          label: "PCIe GPU 1",
          pointsPx: [79, 498, 591, 501, 594, 582, 71, 580],
          sourceWidth: 1280,
          sourceHeight: 963,
          content: {
            title: "PCIe GPU 1",
            what: "A graphics processing unit installed in a PCIe slot, containing the GPU chip, memory, and power delivery components.",
            role: "Accelerates parallel computing tasks like AI training, inference, and scientific simulations.",
          },
        },
        {
          id: "pcie-gpu-2-top",
          label: "PCIe GPU 2",
          pointsPx: [81, 257, 627, 262, 623, 341, 82, 329],
          sourceWidth: 1280,
          sourceHeight: 963,
          content: {
            title: "PCIe GPU 2",
            what: "A graphics processing unit installed in a PCIe slot, containing the GPU chip, memory, and power delivery components.",
            role: "Accelerates parallel computing tasks like AI training, inference, and scientific simulations.",
          },
        },
        {
          id: "nic-top",
          label: "NIC",
          pointsPx: [
            53, 751, 72, 750, 179, 709, 417, 710, 391, 742, 308, 745, 297, 761,
            209, 767, 208, 753, 135, 756, 70, 789, 44, 786,
          ],
          sourceWidth: 1280,
          sourceHeight: 963,
          content: {
            title: "NIC",
            what: "A network interface card that provides network connectivity for data transfer to and from the server.",
            role: "Enables high-speed network communication for data ingestion, model serving, and cluster coordination.",
          },
        },
        {
          id: "host-memory-1-top",
          label: "Host memory (RAM)",
          pointsPx: [705, 147, 707, 236, 770, 172, 922, 171, 923, 142],
          sourceWidth: 1280,
          sourceHeight: 963,
          content: {
            title: "Host memory (RAM)",
            what: "DDR memory modules that provide fast, temporary storage for data and code the CPU is actively processing.",
            role: "Enables quick access to data for the CPU, improving overall system performance and responsiveness.",
          },
        },
        {
          id: "host-memory-2-top",
          label: "Host memory (RAM)",
          pointsPx: [
            694, 374, 698, 432, 781, 432, 785, 467, 922, 467, 921, 370,
          ],
          sourceWidth: 1280,
          sourceHeight: 963,
          content: {
            title: "Host memory (RAM)",
            what: "DDR memory modules that provide fast, temporary storage for data and code the CPU is actively processing.",
            role: "Enables quick access to data for the CPU, improving overall system performance and responsiveness.",
          },
        },
        {
          id: "host-memory-3-top",
          label: "Host memory (RAM)",
          pointsPx: [
            699, 574, 697, 524, 758, 505, 783, 483, 925, 483, 927, 577,
          ],
          sourceWidth: 1280,
          sourceHeight: 963,
          content: {
            title: "Host memory (RAM)",
            what: "DDR memory modules that provide fast, temporary storage for data and code the CPU is actively processing.",
            role: "Enables quick access to data for the CPU, improving overall system performance and responsiveness.",
          },
        },
        {
          id: "host-memory-4-top",
          label: "Host memory (RAM)",
          pointsPx: [919, 710, 695, 710, 696, 810, 929, 815],
          sourceWidth: 1280,
          sourceHeight: 963,
          content: {
            title: "Host memory (RAM)",
            what: "DDR memory modules that provide fast, temporary storage for data and code the CPU is actively processing.",
            role: "Enables quick access to data for the CPU, improving overall system performance and responsiveness.",
          },
        },
        {
          id: "cpu-top",
          label: "CPU",
          pointsPx: [757, 601, 755, 689, 875, 688, 874, 595],
          sourceWidth: 1280,
          sourceHeight: 963,
          content: {
            title: "CPU",
            what: "The central processing unit is the main processor that runs the operating system and coordinates all hardware components.",
            role: "Executes instructions, manages system resources, and handles workloads not suited for GPU acceleration.",
          },
        },
        {
          id: "fan-cooling-tower-top",
          label: "Fan + cooling tower assembly",
          pointsPx: [
            717, 251, 716, 370, 916, 368, 947, 346, 943, 178, 769, 177, 750,
            215, 737, 246,
          ],
          sourceWidth: 1280,
          sourceHeight: 963,
          content: {
            title: "Fan + cooling tower assembly",
            what: "A cooling tower with an attached fan that draws air through the server to remove heat generated by components.",
            role: "Keeps the CPU and other components within safe operating temperatures during heavy workloads.",
          },
        },
        {
          id: "internal-fan",
          label: "Internal fan",
          pointsPx: [
            1000, 259, 999, 405, 1069, 404, 1138, 387, 1140, 214, 1065, 214,
          ],
          sourceWidth: 1280,
          sourceHeight: 963,
          content: {
            title: "Internal fan",
            what: "A cooling fan that circulates air inside the chassis to maintain optimal operating temperatures.",
            role: "Provides additional airflow to cool components and prevent thermal throttling.",
          },
        },
        {
          id: "chassis-intrusion-detector",
          label: "Chassis intrusion detector",
          pointsPx: [
            1143, 944, 1164, 961, 1209, 959, 1205, 942, 1181, 922, 1155, 920,
            1205, 786, 1196, 783, 1133, 925,
          ],
          sourceWidth: 1280,
          sourceHeight: 963,
          content: {
            title: "Chassis intrusion detector",
            what: "A sensor that detects when the server chassis has been opened or tampered with.",
            role: "Provides security monitoring and alerts administrators to unauthorized physical access.",
          },
        },
        {
          id: "pcie-cable-mcio",
          label: "PCIe cable (Slim SAS)",
          pointsPx: [
            609, 597, 637, 578, 653, 578, 648, 655, 596, 658, 593, 641, 505,
            630, 446, 632, 337, 623, 337, 586, 364, 587, 450, 587, 505, 585,
          ],
          sourceWidth: 1280,
          sourceHeight: 963,
          content: {
            title: "PCIe cable (Slim SAS)",
            what: "A high-speed cable connector used to link PCIe devices, commonly used for GPU to GPU communication.",
            role: "Enables data transfer between GPUs and the motherboard for compute and memory access.",
          },
        },
        {
          id: "power-cable-pcie-gpu-1",
          label: "Power cable for PCIe GPU 1",
          pointsPx: [
            593, 511, 657, 511, 733, 492, 767, 464, 764, 446, 735, 443, 698,
            472, 683, 501, 655, 557, 618, 590, 578, 594, 579, 584, 610, 574,
            637, 526, 674, 470, 731, 431, 771, 436, 779, 458, 773, 486, 746,
            508, 705, 520, 612, 523, 609, 532, 588, 531,
          ],
          sourceWidth: 1280,
          sourceHeight: 963,
          content: {
            title: "Power cable for PCIe GPU 1",
            what: "An auxiliary power cable that delivers additional electricity to the GPU beyond what the PCIe slot provides.",
            role: "Supplies the high current needed by GPUs for compute workloads, preventing power starvation.",
          },
        },
      ],
    },
    {
      id: "back",
      src: "images/back.png",
      alt: "GPU server, back view",
      hotspots: [
        {
          id: "pcie-gpu-1-back",
          label: "PCIe GPU 1",
          pointsPx: [678, 272, 688, 574, 792, 572, 749, 263],
          sourceWidth: 1280,
          sourceHeight: 963,
          content: {
            title: "PCIe GPU 1",
            what: "A graphics processing unit installed in a PCIe slot, containing the GPU chip, memory, and power delivery components.",
            role: "Accelerates parallel computing tasks like AI training, inference, and scientific simulations.",
          },
        },
        {
          id: "pcie-gpu-2-back",
          label: "PCIe GPU 2",
          pointsPx: [
            531, 266, 504, 263, 504, 254, 482, 253, 384, 568, 417, 721, 452,
            715, 474, 562, 514, 523, 548, 365,
          ],
          sourceWidth: 1280,
          sourceHeight: 963,
          content: {
            title: "PCIe GPU 2",
            what: "A graphics processing unit installed in a PCIe slot, containing the GPU chip, memory, and power delivery components.",
            role: "Accelerates parallel computing tasks like AI training, inference, and scientific simulations.",
          },
        },
        {
          id: "nic-back",
          label: "NIC",
          pointsPx: [
            898, 507, 920, 419, 939, 436, 957, 495, 975, 495, 994, 548, 990,
            568, 999, 585, 1009, 565, 1054, 565, 997, 746, 955, 746, 967, 703,
          ],
          sourceWidth: 1280,
          sourceHeight: 963,
          content: {
            title: "NIC",
            what: "A network interface card that provides network connectivity for data transfer to and from the server.",
            role: "Enables high-speed network communication for data ingestion, model serving, and cluster coordination.",
          },
        },
        {
          id: "psu-1",
          label: "Power supply unit 1",
          pointsPx: [182, 799, 348, 798, 365, 849, 205, 846],
          sourceWidth: 1280,
          sourceHeight: 963,
          content: {
            title: "Power supply unit 1",
            what: "A modular power supply unit that converts AC power from the wall to DC power for server components.",
            role: "Provides reliable, efficient power delivery to all hardware components in the server.",
          },
        },
        {
          id: "psu-2",
          label: "Power supply unit 2",
          pointsPx: [347, 797, 366, 852, 523, 848, 511, 790],
          sourceWidth: 1280,
          sourceHeight: 963,
          content: {
            title: "Power supply unit 2",
            what: "A modular power supply unit that converts AC power from the wall to DC power for server components.",
            role: "Provides reliable, efficient power delivery to all hardware components in the server.",
          },
        },
        {
          id: "psu-3",
          label: "Power supply unit 3",
          pointsPx: [805, 790, 797, 843, 965, 842, 979, 792],
          sourceWidth: 1280,
          sourceHeight: 963,
          content: {
            title: "Power supply unit 3",
            what: "A modular power supply unit that converts AC power from the wall to DC power for server components.",
            role: "Provides reliable, efficient power delivery to all hardware components in the server.",
          },
        },
        {
          id: "psu-4",
          label: "Power supply unit 4",
          pointsPx: [981, 791, 965, 846, 1133, 847, 1159, 787],
          sourceWidth: 1280,
          sourceHeight: 963,
          content: {
            title: "Power supply unit 4",
            what: "A modular power supply unit that converts AC power from the wall to DC power for server components.",
            role: "Provides reliable, efficient power delivery to all hardware components in the server.",
          },
        },
      ],
    },
    {
      id: "cables",
      src: "images/cables.jpg",
      alt: "Cables detail view",
      hotspots: [
        {
          id: "power-cable-pcie-gpu-1-cables",
          label: "Power cable for PCIe GPU 1",
          pointsPx: [
            2644, 751, 2767, 817, 2758, 838, 2896, 946, 3160, 1066, 3499, 1183,
            3775, 1258, 3947, 1300, 3905, 1372, 3908, 1423, 3869, 1426, 3745,
            1510, 3655, 1534, 3142, 1483, 2941, 1546, 2734, 1669, 2454, 1765,
            2139, 1844, 2121, 1729, 2397, 1621, 2559, 1543, 2752, 1489, 2983,
            1435, 3055, 1408, 3313, 1351, 3412, 1336, 3220, 1255, 3013, 1174,
            2785, 1087, 2662, 1027, 2638, 1054, 2508, 991, 2565, 814,
          ],
          sourceWidth: 4080,
          sourceHeight: 3072,
          content: {
            title: "Power cable for PCIe GPU 1",
            what: "An auxiliary power cable that delivers additional electricity to the GPU beyond what the PCIe slot provides.",
            role: "Supplies the high current needed by GPUs for compute workloads, preventing power starvation.",
          },
        },
        {
          id: "pcie-cable-mcio-cables",
          label: "PCIe cable (Slim SAS)",
          pointsPx: [
            833, 1030, 1010, 925, 1226, 1087, 1376, 1132, 1476, 1204, 1638,
            1384, 2118, 1666, 2157, 2015, 2325, 2111, 2262, 2234, 2196, 2183,
            2052, 2237, 1812, 2060, 1815, 2012, 1902, 1874, 1470, 1582, 1313,
            1468, 1124, 1306, 1148, 1270, 1034, 1225, 821, 1051,
          ],
          sourceWidth: 4080,
          sourceHeight: 3072,
          content: {
            title: "PCIe cable (Slim SAS)",
            what: "A high-speed cable connector used to link PCIe devices, commonly used for GPU to GPU communication.",
            role: "Enables data transfer between GPUs and the motherboard for compute and memory access.",
          },
        },
        {
          id: "power-sockets",
          label: "Power sockets",
          pointsPx: [1803, 2048, 1373, 2480, 1521, 2618, 1944, 2168],
          sourceWidth: 4080,
          sourceHeight: 3072,
          content: {
            title: "Power sockets",
            what: "Connectors that receive power cables from the power supply units to deliver electricity to components.",
            role: "Provides secure, modular connections for distributing power throughout the server.",
          },
        },
        {
          id: "pcie-cable-sockets",
          label: "PCIe cable sockets",
          pointsPx: [
            1926, 2234, 2103, 2396, 1500, 3066, 1277, 3066, 1199, 2999,
          ],
          sourceWidth: 4080,
          sourceHeight: 3072,
          content: {
            title: "PCIe cable sockets",
            what: "Ports on the motherboard or riser cards that accept PCIe Slim SAS cables for device connectivity.",
            role: "Enables high-bandwidth data links between GPUs, storage, and other expansion devices.",
          },
        },
      ],
    },
    {
      id: "gpu",
      src: "images/GPU.jpg",
      alt: "GPU detail view",
      hotspots: [
        {
          id: "gpu-chip-die",
          label: "GPU chip (die)",
          pointsPx: [245, 239, 282, 346, 435, 346, 415, 236],
          sourceWidth: 1180,
          sourceHeight: 592,
          content: {
            title: "GPU chip (die)",
            what: "The main silicon processor containing thousands of cores designed for parallel computation.",
            role: "Executes massively parallel workloads like neural network training and inference.",
          },
        },
        {
          id: "heatsink-1",
          label: "Heatsink 1",
          pointsPx: [
            434, 194, 422, 249, 454, 447, 677, 452, 707, 248, 701, 197,
          ],
          sourceWidth: 1180,
          sourceHeight: 592,
          content: {
            title: "Heatsink 1",
            what: "A metal heatsink with fins that absorbs and dissipates heat from the GPU chip into the air.",
            role: "Keeps the GPU operating within safe temperature limits during intensive compute tasks.",
          },
        },
        {
          id: "heatsink-2",
          label: "Heatsink 2",
          pointsPx: [
            706, 198, 712, 253, 682, 456, 995, 458, 1122, 250, 1099, 195,
          ],
          sourceWidth: 1180,
          sourceHeight: 592,
          content: {
            title: "Heatsink 2",
            what: "A metal heatsink with fins that absorbs and dissipates heat from the GPU chip into the air.",
            role: "Keeps the GPU operating within safe temperature limits during intensive compute tasks.",
          },
        },
      ],
    },
    {
      id: "gpu_back",
      src: "images/GPU_back.png",
      alt: "GPU back view",
      hotspots: [
        {
          id: "gpu-memory-back",
          label: "GPU memory",
          pointsPx: [236, 263, 237, 325, 532, 323, 528, 258],
          sourceWidth: 1280,
          sourceHeight: 963,
          content: {
            title: "GPU memory",
            what: "High-bandwidth memory modules (HBM or GDDR) mounted on the back of the GPU card.",
            role: "Provides fast local storage for data being processed by the GPU, reducing CPU-GPU data transfers.",
          },
        },
        {
          id: "gpu-chip-back",
          label: "GPU chip (back)",
          pointsPx: [448, 372, 451, 573, 257, 577, 258, 376],
          sourceWidth: 1280,
          sourceHeight: 963,
          content: {
            title: "GPU chip (back)",
            what: "The main silicon processor containing thousands of cores designed for parallel computation.",
            role: "Executes massively parallel workloads like neural network training and inference.",
          },
        },
        {
          id: "pcie-fins",
          label: "PCIe fins",
          pointsPx: [
            621, 690, 622, 711, 600, 714, 606, 737, 655, 733, 657, 704, 667,
            705, 668, 745, 1056, 737, 1054, 680,
          ],
          sourceWidth: 1280,
          sourceHeight: 963,
          content: {
            title: "PCIe fins",
            what: "Metal fins on the PCIe connector that provide electrical shielding and signal integrity.",
            role: "Ensures stable high-speed data transfer between the GPU and motherboard.",
          },
        },
        {
          id: "gpu-chip-power-system",
          label: "GPU chip power system",
          pointsPx: [
            490, 367, 490, 384, 530, 386, 534, 416, 534, 436, 491, 436, 492,
            599, 531, 600, 534, 587, 574, 584, 569, 353,
          ],
          sourceWidth: 1280,
          sourceHeight: 963,
          content: {
            title: "GPU chip power system",
            what: "Power delivery components including VRMs and capacitors that regulate and distribute power to the GPU.",
            role: "Ensures stable, clean power delivery to the GPU for reliable operation under heavy loads.",
          },
        },
      ],
    },
    {
      id: "drive_bays",
      src: "images/drive_bays.png",
      alt: "Drive bays view",
      hotspots: [
        {
          id: "drive-bays",
          label: "Drive bays",
          pointsPx: [138, 661, 1154, 663, 1148, 846, 139, 844],
          sourceWidth: 1280,
          sourceHeight: 963,
          content: {
            title: "Drive bays",
            what: "Hot-swappable slots for installing SSDs or HDDs for local data storage.",
            role: "Provides fast, reliable storage for the operating system, applications, and datasets.",
          },
        },
        {
          id: "fan-bays",
          label: "Fan bays",
          pointsPx: [133, 444, 138, 640, 1161, 642, 1166, 455],
          sourceWidth: 1280,
          sourceHeight: 963,
          content: {
            title: "Fan bays",
            what: "Mounting locations for cooling fans that pull air through the front of the server.",
            role: "Provides primary cooling airflow to maintain optimal operating temperatures.",
          },
        },
        {
          id: "power-buttons-leds",
          label: "Power buttons and LED lights",
          pointsPx: [50, 732, 91, 732, 94, 866, 53, 865],
          sourceWidth: 1280,
          sourceHeight: 963,
          content: {
            title: "Power buttons and LED lights",
            what: "Physical buttons and status indicators for power control and system health monitoring.",
            role: "Allows manual power control and provides visual feedback on drive activity and system status.",
          },
        },
      ],
    },
  ],
};
